# Generated by Django 5.2.3 on 2025-06-24 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botanik_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AccessionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_number', models.CharField(blank=True, max_length=10, unique=True)),
                ('taxon_name', models.CharField(max_length=100)),
                ('material_type', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('coordinates', models.CharField(blank=True, max_length=50, null=True)),
                ('collection_date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botanik_core.collector')),
            ],
        ),
    ]
