# Generated by Django 5.2.3 on 2025-06-26 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botanik_core', '0002_collector_is_active_accessionrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedBankRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_description', models.TextField(max_length=200)),
                ('storage_location', models.CharField(max_length=50)),
                ('storage_date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botanik_core.accessionrecord')),
            ],
        ),
    ]
