# Generated by Django 5.2.3 on 2025-06-27 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botanik_core', '0003_seedbankrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='HerbariumRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herbarium_number', models.CharField(max_length=50, unique=True)),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='herbarium_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botanik_core.accessionrecord')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botanik_core.collector')),
            ],
        ),
    ]
