# Generated by Django 5.2.3 on 2025-06-29 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botanik_core', '0004_herbariumrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sub_location', models.CharField(blank=True, max_length=100, null=True)),
                ('island_code', models.PositiveSmallIntegerField()),
                ('sub_code', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantStatusRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('vegetative_state', models.CharField(blank=True, max_length=100, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botanik_core.accessionrecord')),
                ('garden_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botanik_core.gardenlocation')),
            ],
        ),
    ]
