# Generated by Django 5.2.3 on 2025-07-01 11:57

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botanik_core', '0005_gardenlocation_plantstatusrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessionrecord',
            name='collection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collector',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
