# Generated by Django 5.2.3 on 2025-07-04 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botanik_core', '0006_alter_accessionrecord_collection_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TablePermissionArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'İzin Verilecek Tablo (TablePermissionArea)',
                'verbose_name_plural': 'İzin Verilecek Tablolar (TablePermissionArea)',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kullanıcı Grubu (UserGroup)',
                'verbose_name_plural': 'Kullanıcı Grupları (UserGroup)',
            },
        ),
        migrations.AlterField(
            model_name='plantstatusrecord',
            name='accession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botanik_core.accessionrecord'),
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('deletion_permission', models.CharField(choices=[('no', 'Hayır'), ('yes', 'Evet'), ('with_approval', 'Yönetici Onayıyla')], default='no', max_length=20)),
                ('can_add_tables', models.ManyToManyField(blank=True, related_name='addable_by_users', to='botanik_core.tablepermissionarea')),
                ('can_view_tables', models.ManyToManyField(blank=True, related_name='viewable_by_users', to='botanik_core.tablepermissionarea')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('user_group', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='botanik_core.usergroup')),
            ],
            options={
                'verbose_name': 'Kullanıcı Yetkisi (UserPermission)',
                'verbose_name_plural': 'Kullanıcı Yetkileri (UserPermission)',
            },
        ),
    ]
