# Generated by Django 5.2.4 on 2025-07-08 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botanik_core', '0009_collector_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='user_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botanik_core.usergroup'),
        ),
    ]
