# Generated by Django 5.2.4 on 2025-07-10 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botanik_core', '0010_alter_userpermission_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collector',
            name='email',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='name',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='surname',
        ),
    ]
