# Generated by Django 5.2.4 on 2025-07-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botanik_core', '0012_alter_collector_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessionrecord',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
